### ISSUE TITLE
missing assential basic functionallity

### ISSUE THREAD

**Issue by jayraj2610** [dev-iamsaurabh/JPIETCollegeAdminApp#1]
no option for 

- deleting PDF 
- deleting gallery image
- restricting spam accounts

dark mode will not work correctly for devices using higher than Android 10 
you have to add **android:forceDarkAllowed: false**

**Comment by dev-iamsaurabh** [comment]
Dear jayraj,
This is just a sample app for learning purpose and my first android project.I have given the option for Delete notice once you learn from it. you can implement all deleting operations your own in other sections of the app. 🙌
Apart from that , I have already described what you can do with this App in readme section . You can clone it make those  features and contribute to open source for others. 😄 
Last thing i fogot to mention that , Theme section is incompleted. I will update my readme file ASAP .

**Comment by dev-iamsaurabh** [comment]
Closing this Issue, cuz its solved ;)

**Comment by jayraj2610** [comment]
I have been working on it. its partially implemented 
I have also implemented the upload progress bar.

**Comment by dev-iamsaurabh** [comment]
Great ☺️ BTW i visited your linkdin you are a good game developer all the best for your future.

**Comment by jayraj2610** [comment]
thanks
